spring.application.name=lab15

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=55fa2d1a2e2431
spring.mail.password=663925b0a9b1d0
spring.mail.properties.mail.smtp.auth=PLAIN
